import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-full h-screen flex items-center justify-center'>
        <h1 className='text-2xl text-teal-500 font-bold'>Welcome to next js</h1>
      </main>
    </div>
  );
}
